import assert from 'node:assert/strict';
import { mkdir } from 'node:fs/promises';
const { chromium } = await import(process.env.PLAYWRIGHT_MODULE || 'playwright');
const browser = await chromium.launch({ headless: true, channel: 'chrome', args: ['--no-sandbox'] });
const context = await browser.newContext({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 3, isMobile: true, hasTouch: true });
const page = await context.newPage();
const errors = [];
page.on('pageerror', error => errors.push(error.message));
await mkdir('artifacts', { recursive: true });
await page.goto('http://127.0.0.1:4173');
await page.getByText('年号暗記', { exact: true }).first().waitFor();
assert.equal(await page.locator('.brand-mark').evaluate(image => image.complete && image.naturalWidth > 0), true);
assert.match(await page.locator('link[rel="apple-touch-icon"]').getAttribute('href'), /seikei-icon\.png/);
await page.screenshot({ path: 'artifacts/mobile-home.png', fullPage: true });

await page.getByRole('button', { name: /年号暗記/ }).click();
const before = await page.locator('.keypad').boundingBox();
for (const digit of ['1','2','3','4']) await page.locator(`[data-key="${digit}"]`).click();
await page.getByRole('button', { name: /回答する/ }).click();
assert.match(await page.locator('.answer-feedback').innerText(), /正しい西暦は/);
const after = await page.locator('.keypad').boundingBox();
assert.equal(before.y, after.y, 'keypad should stay in place after answering');
await page.screenshot({ path: 'artifacts/mobile-year-result.png', fullPage: true });
await page.getByRole('button', { name: /次の問題/ }).click();
await page.getByRole('button', { name: 'ホームに戻る' }).click();

await page.getByRole('button', { name: /年代整序/ }).click();
assert.equal(await page.locator('.order-card').count(), 4);
const firstBeforeDrag = await page.locator('.order-title').first().innerText();
const handle = await page.locator('.drag-handle').first().boundingBox();
const last = await page.locator('.order-card').last().boundingBox();
const cdp = await context.newCDPSession(page);
const touchX = handle.x + handle.width / 2;
const touchY = handle.y + handle.height / 2;
await cdp.send('Input.dispatchTouchEvent', { type: 'touchStart', touchPoints: [{ x: touchX, y: touchY, id: 1 }] });
for (let step = 1; step <= 8; step++) {
  await cdp.send('Input.dispatchTouchEvent', { type: 'touchMove', touchPoints: [{ x: touchX, y: touchY + (last.y + last.height / 2 - touchY) * step / 8, id: 1 }] });
}
await cdp.send('Input.dispatchTouchEvent', { type: 'touchEnd', touchPoints: [] });
assert.notEqual(await page.locator('.order-title').first().innerText(), firstBeforeDrag);
await page.locator('[data-move="down"]').first().click();
await page.getByRole('button', { name: /この順番で回答/ }).click();
assert.equal(await page.locator('.timeline li').count(), 4);
await page.screenshot({ path: 'artifacts/mobile-order-result.png', fullPage: true });
await page.getByRole('button', { name: 'ホームに戻る' }).click();

await page.getByRole('button', { name: /履歴・復習/ }).click();
assert.match(await page.locator('.stats').innerText(), /2/);
await page.reload();
await page.getByRole('button', { name: /履歴・復習/ }).click();
assert.match(await page.locator('.stats').innerText(), /2/);
await page.getByRole('button', { name: '年号で復習' }).click();
assert.match(await page.locator('.quiz-meta').innerText(), /間違えたものを復習/);
await page.getByRole('button', { name: 'ホームに戻る' }).click();
await page.getByRole('button', { name: /学習範囲を設定/ }).click();
assert.equal(await page.locator('[data-importance]').count(), 4);
assert.equal(await page.locator('[data-importance]:checked').count(), 2);
await page.getByText('標準', { exact: true }).click();
assert.equal(await page.locator('[data-importance]:checked').count(), 3);
await page.screenshot({ path: 'artifacts/mobile-settings.png', fullPage: true });
await page.getByRole('button', { name: 'すべて外す' }).click();
await page.getByRole('button', { name: '設定を保存して戻る' }).click();
await page.getByRole('button', { name: /年号暗記/ }).click();
assert.match(await page.locator('.empty-state').innerText(), /出題できる出来事がない/);
await page.locator('.empty-state [data-action="home"]').click();
await page.getByRole('button', { name: /履歴・復習/ }).click();
page.once('dialog', dialog => dialog.dismiss());
await page.getByRole('button', { name: '履歴と復習対象を削除' }).click();
assert.match(await page.locator('.stats').innerText(), /2/);
page.once('dialog', dialog => dialog.accept());
await page.getByRole('button', { name: '履歴と復習対象を削除' }).click();
assert.match(await page.locator('.stats').innerText(), /0/);
assert.deepEqual(errors, []);
await browser.close();
console.log('Mobile UI flow passed; screenshots in artifacts/.');
